### PR TITLE
Update ember and core

### PR DESCRIPTION
**Pull request by dafortin**
#major#

Note: 
* There is an error produce by the coverage. We will have to update the coverage eventually once `ember-cli-code-coverage` is fixed.
* We need to enable sass linting and rework the scss files (https://github.com/ciena-frost/ember-frost-demo-components/issues/16)

# CHANGELOG
* **Updated** `ember@~2.8.0`
* **Updated** `ember-frost-core@^1.0.0`
* **Added/updated** linting and coverage

### CODE REVIEW

**Comment by rox163** [comment]
What is the coverage error? Is it happening with v 0.3.5?

**Comment by dafortin** [comment]
It's not able to handle the @readonly
```
Unable to cover: modules/ember-frost-demo-components/components/frost-file-node/component.js . Try setting useBabelInstrumenter to true.
 SyntaxError: modules/ember-frost-demo-components/components/frost-file-node/component.js: Unexpected token (26:2)
  },

  @readOnly
  @computed('fileNode')
  isFolder (fileNode) {
    return fileNode.type === 'directory'
  at Parser.pp.raise (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/location.js:24:13)
  at Parser.pp.unexpected (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/util.js:82:8)
  at Parser.pp.parseDecorator (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/statement.js:170:10)
  at Parser.pp.parseObj (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:601:28)
  at Parser.pp.parseExprAtom (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:392:19)
  at Parser.parseExprAtom (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/plugins/jsx/index.js:412:22)
  at Parser.pp.parseExprSubscripts (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:236:19)
  at Parser.pp.parseMaybeUnary (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:217:19)
  at Parser.pp.parseExprOps (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:163:19)
  at Parser.pp.parseMaybeConditional (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:145:19)
  at Parser.pp.parseMaybeAssign (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:112:19)
  at Parser.pp.parseExprListItem (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:801:16)
  at Parser.parseExprListItem (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/plugins/flow.js:819:24)
  at Parser.pp.parseExprList (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:789:20)
  at Parser.pp.parseSubscripts (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:270:29)
  at Parser.pp.parseExprSubscripts (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:240:17)
  at Parser.pp.parseMaybeUnary (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:217:19)
  at Parser.pp.parseExprOps (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:163:19)
  at Parser.pp.parseMaybeConditional (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:145:19)
  at Parser.pp.parseMaybeAssign (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/expression.js:112:19)
  at Parser.pp.parseExport (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/statement.js:682:21)
  at Parser.parseExport (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/plugins/flow.js:713:20)
  at Parser.pp.parseStatement (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/statement.js:115:90)
  at Parser.parseStatement (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/plugins/flow.js:655:22)
  at Parser.pp.parseTopLevel (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/statement.js:30:21)
  at Parser.parse (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/parser/index.js:70:17)
  at Object.parse (/Users/dafortin/code/ember-frost-demo-components/node_modules/babylon/lib/index.js:45:50)
  at Object.exports.default (/Users/dafortin/code/ember-frost-demo-components/node_modules/babel-core/lib/helpers/parse.js:36:18)
  at File.parse (/Users/dafortin/code/ember-frost-demo-components/node_modules/babel-core/lib/transformation/file/index.js:574:40)
  at File.parseCode (/Users/dafortin/code/ember-frost-demo-components/node_modules/babel-core/lib/transformation/file/index.js:691:20)
  at /Users/dafortin/code/ember-frost-demo-components/node_modules/babel-core/lib/transformation/pipeline.js:167:12
  at File.wrap (/Users/dafortin/code/ember-frost-demo-components/node_modules/babel-core/lib/transformation/file/index.js:639:16)
  at Pipeline.transform (/Users/dafortin/code/ember-frost-demo-components/node_modules/babel-core/lib/transformation/pipeline.js:165:17)
  at Instrumenter.instrumentSync (/Users/dafortin/code/ember-frost-demo-components/node_modules/ember-cli-code-coverage/lib/babel-istanbul-instrumenter.js:36:45)
  at CoverageInstrumenter.processString (/Users/dafortin/code/ember-frost-demo-components/node_modules/ember-cli-code-coverage/lib/coverage-instrumenter.js:102:25)
  at CoverageInstrumenter.processFile (/Users/dafortin/code/ember-frost-demo-components/node_modules/broccoli-filter/index.js:165:31)
  at asyncProcessFile (/Users/dafortin/code/ember-frost-demo-components/node_modules/broccoli-filter/index.js:122:21)
  at tryCatch (/Users/dafortin/code/ember-frost-demo-components/node_modules/rsvp/dist/rsvp.js:538:12)
  at invokeCallback (/Users/dafortin/code/ember-frost-demo-components/node_modules/rsvp/dist/rsvp.js:553:13)
  at /Users/dafortin/code/ember-frost-demo-components/node_modules/rsvp/dist/rsvp.js:628:16
  at flush (/Users/dafortin/code/ember-frost-demo-components/node_modules/rsvp/dist/rsvp.js:2373:5)
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by sandersky** [comment]
@dafortin try copying the file at `config/coverage.js` into `tests/dummy/config/coverage.js` as well.

**Comment by dafortin** [comment]
same error

**Comment by rox163** [comment]
do you have this in ember-cli-build?
    babel: {
      optional: ['es7.decorators']
    }

**Comment by dafortin** [comment]
Ahh that was the fix :)

**Comment by rox163** [comment]
:+1:

**Pull request merged**
